access_token = "your.webex.token"
teams_room = "your.teams.room.id"
http_proxy  = "http://proxy.your.server.com:port"
webex_webhook_url = "https://your.webhook.url"
slack_webhook_url = "https://your.webhook.url"
microsoft_webhook_url = "https://your.webhook.url"
