access_token = "your webex token"
teams_room = "your teams room id"
http_proxy  = "http://your.proxy.server.com:port"
webex_webhook_url = "https://hooks.slack.com/services/xxx/yyy/zzz"
slack_webhook_url = "https://hooks.slack.com/services/xxx/yyy/zzz"
microsoft_webhook_url = "https://hooks.slack.com/services/xxx/yyy/zzz"
